name: deploy to lambda
on: [workflow_dispatch]
jobs:
  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest
    needs: run_tests
    strategy:
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: npm install
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm install
      - name: create zip file
        run: |
          zip ribot/latest.zip .
      - name: default deploy
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ribot
          zip_file: ribot/latest.zip
          memory_size: 128
          timeout: 5
          handler: handler
          role: arn:aws:iam::788704922800:role/ribot-lambda-role
          runtime: nodejs18.x