name: deploy to lambda
on: [workflow_dispatch]
jobs:
  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - run: npm test
  deploy_zip:
    name: Deploy lambda function
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - name: checkout source code
        uses: actions/checkout@v4
      - name: npm install
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - run: npm install
      - name: create zip file
        run: |
          zip -r9 latest.zip .
      - name: default deploy
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ribot-webhook
          zip_file: latest.zip
          memory_size: 128
          timeout: 5
          handler: index.handler
          role: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ribot-lambda-role
          runtime: nodejs18.x
